### ISSUE TITLE
[TODO] 토너먼트 페이지 만들기

### ISSUE THREAD

**Issue by hleesa** [bukdu7seong/FE#10]
## Todo List

**작업 목록:**

토너먼트 페이지 SPA로 만들기

- [x] 작업 1 : 토너먼트 정보 입력 모달 만들기. player nickname, game mode
- [x] 작업 2 : 라운드 시작 모달 만들기. 
- [x] 작업 3 : 토너먼트 종료 및 우승자 알림 모달
- [x] 작업 4 : 토너먼트 게임 진행

**Comment by sideseal** [comment]
모두 처리되어서 이슈 닫습니다!
